"""Add username and full_name to users

Revision ID: 0004_add_user_details
Revises: 0003_active_dialogs_guard
Create Date: 2026-02-12 23:55:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004_add_user_details'
down_revision: Union[str, None] = '0003_active_dialogs_guard'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
